import Head from "next/head";
import ProductCard from "../components/cards/ProductCard";
import ReviewCard from "../components/cards/ReviewCard";
import InputSearch from "./../components/element/InputSearch";
import HeadSection from "./../components/element/HeadSection";
import Benfits from "./../components/section/Benfits";
import Image from "next/image";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation } from "swiper";
import {fetchApi} from "../hooks/useApi";


import "swiper/css";
import "swiper/css/navigation";


export default function Home({products,error}) {

  const productList = products.map((product) => {
    return (
        <SwiperSlide key={product.id}>
          <ProductCard   productData={product}/>
        </SwiperSlide>
    );
  });

  return (
    <>
      <Head>
        <title>Lalasia - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://stijndv.com" />
      </Head>

      <section className="hero py-14">
        <div className="container relative">
          <span className="absolute top-0 left-0 ">
            <Image
              src="/icons/arrow.png"
              width="200%"
              height="200%"
              layout="fixed"
              alt="arrow"
            />
          </span>
          <div className="text-center m-auto w-full lg:w-4/5">
            <h1 className="text-h2 sm:text-h1 mb-3">
              Discover Furniture With High Quality Wood
            </h1>
            <p className="text-p2 sm:text-p1 text-base">
              Pellentesque etiam blandit in tincidunt at donec. Eget ipsum
              dignissim placerat nisi, adipiscing mauris non. Purus parturient
              viverra nunc, tortor sit laoreet. Quam tincidunt aliquam
              adipiscing tempor.
            </p>
          </div>
          <div className="relative mt-28 lg:mt-16 w-full h-4/5">
            <div className="absolute z-40	 w-full lg:w-4/5 inset-x-1/2 -top-24 lg:-top-8	-translate-x-1/2	">
              <InputSearch />
            </div>
            <Image
              src="/hero.png"
              width={900}
              height={450}
              layout="responsive"
              objectFit="cover"
              alt="arrow"
            />
          </div>
        </div>
      </section>

      <Benfits />

      <section className="py-16">
        <div className="container">
          <HeadSection 
              name="Product"
              title="Our popular products"
              text="Pellentesque etiam blandit in tincidunt at donec. Eget ipsum dignissim placerat nisi, adipiscing mauris non purus parturient."
              center={true}
          />
          {error ? 
          <p className="text-red-500 text-h5 p-5 bg-red-100 rounded">{error}</p>
          : 
          <>
            {products.length === 0 ? 
            <p className="text-red-500 text-h5 p-5 bg-red-100 rounded">search not found</p>
            :
            <Swiper
            breakpoints={{
              0: {
                slidesPerView: 1,
                spaceBetween: 30,
              },
              768: {
                slidesPerView: 2,
                spaceBetween: 20,
              },
              1024: {
                slidesPerView: 3,
                spaceBetween: 30,
              },
              1536: {
                slidesPerView: 4,
                spaceBetween: 40,
              }, 
            }}
            navigation={true}
            pagination={{
              clickable: true,
            }}
            modules={[Navigation]}
            className="py-12"
          >
          {productList}
          </Swiper>
          }
          </>
          }
         
        </div>
      </section>

      
      <section className="py-16">
        <div className="container">
        <HeadSection 
              name="Testimonials"
              title="What our customer say"
              text="Pellentesque etiam blandit in tincidunt at donec. Eget ipsum dignissim placerat nisi, adipiscing mauris non purus parturient."
              center={true}
          />
          <Swiper
            breakpoints={{
              0: {slidesPerView: 1},
              768: {slidesPerView: 2},
              1024: {slidesPerView: 3},
              1536: {slidesPerView: 4}, 
            }}
            spaceBetween={20}

            navigation={true}
            pagination={{
              clickable: true,
            }}
            modules={[Navigation]}
          >
            <SwiperSlide>
              <ReviewCard />
            </SwiperSlide>

            <SwiperSlide>
              <ReviewCard />
            </SwiperSlide>

            <SwiperSlide>
              <ReviewCard />
            </SwiperSlide>

            <SwiperSlide>
              <ReviewCard />
            </SwiperSlide>

          </Swiper>
        </div>
      </section>

    </>
  );
}


export async function getServerSideProps() {
  
  try {
    const products = await fetchApi("products?_start=0&_end=6");
    return {
      props: {
        products,
        error: null,
      },
    };
  } catch (error) {
    return {
      props: {
        products: [],
        error: error,

      }
    };

  }
  return {
    props: {
      products,
    },
  };
}